version: '3.7'
services:
  exchange-rate-service:
    image: shefzee/exchange-rate-service:1.0
    ports:
      - "9091:9091"
    restart: always
    depends_on: # Start the depends_on first
      - mysql 
    environment:
      DB_USER_NAME: shefzee
      DB_PASSWORD: shef123
      PORT: 9091
      SPRING_DATA_URL: jdbc:mysql://mysql:3306/exchange_rate?autoReconnect=true&useSSL=false
    networks:
      - currency-conversion-network
  currency-conversion-service:
    image: shefzee/currency-conversion-service:1.0
    ports:
      - "9092:9092"
    restart: always
    depends_on: # Start the depends_on first
      - mysql 
    environment:
      DB_USER_NAME: shefzee
      DB_PASSWORD: shef123
      PORT: 9092
      SPRING_DATA_URL: jdbc:mysql://mysql:3306/exchange_rate?autoReconnect=true&useSSL=false
      EXCHANGE_RATE_URL: http://exchange-rate-service:9091  
    networks:
      - currency-conversion-network 
   
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root      
      MYSQL_USER: shefzee
      MYSQL_PASSWORD: shef123
      MYSQL_DATABASE: exchange_rate
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
    networks:
      - currency-conversion-network  
  
# Volumes
volumes:
  mysql-database-data-volume:

networks:
  currency-conversion-network: